//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace worldSkills
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorldSkillsDbEntities : DbContext
    {
        public WorldSkillsDbEntities()
            : base("name=WorldSkillsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CompetitionTbl> CompetitionTbls { get; set; }
        public virtual DbSet<CompetitionTimeTbl> CompetitionTimeTbls { get; set; }
        public virtual DbSet<FileTimeTbl> FileTimeTbls { get; set; }
        public virtual DbSet<HardshipTbl> HardshipTbls { get; set; }
        public virtual DbSet<LevelTbl> LevelTbls { get; set; }
        public virtual DbSet<LoginLogTbl> LoginLogTbls { get; set; }
        public virtual DbSet<LogoutLogTbl> LogoutLogTbls { get; set; }
        public virtual DbSet<QuestionFileTbl> QuestionFileTbls { get; set; }
        public virtual DbSet<RullTbl> RullTbls { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<SurvayCountTbl> SurvayCountTbls { get; set; }
        public virtual DbSet<SurvayTbl> SurvayTbls { get; set; }
        public virtual DbSet<SurvayTimeTbl> SurvayTimeTbls { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserTbl> UserTbls { get; set; }
    }
}
