//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace worldSkills
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionFileTbl
    {
        public int QuestionFIleId { get; set; }
        public string QuestionFileName { get; set; }
        public int QuestionCompetitionId { get; set; }
        public int QuestionCompetitionDateTime { get; set; }
        public int QuestionCompetitionLevel { get; set; }
        public int QuestionHardship { get; set; }
        public int QuestionUploadedUser { get; set; }
    }
}
