//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace worldSkills
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurvayTbl
    {
        public int SurvayId { get; set; }
        public int SurvayCompetitionStartTime { get; set; }
        public string SurvayUserNationalCode { get; set; }
        public int SurvayCompetition { get; set; }
    }
}
