//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace worldSkills
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurvayTimeTbl
    {
        public int SurvayTimeId { get; set; }
        public System.DateTime SurvayTimeDate { get; set; }
        public int SurvayStartComDate { get; set; }
        public int SurvayCom { get; set; }
    }
}
