//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace worldSkills
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurvayCountTbl
    {
        public int SurvayCountId { get; set; }
        public int CompetitionId { get; set; }
        public int CompetitionTimeId { get; set; }
    }
}
