//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace worldSkills
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTbl
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserLastName { get; set; }
        public string UserNationalCode { get; set; }
        public string UserPassword { get; set; }
        public System.DateTime UserBirhtday { get; set; }
        public Nullable<int> UserCompetition { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public int UserRull { get; set; }
        public string UserPhoto { get; set; }
        public int UserStateId { get; set; }
        public int UserCityId { get; set; }
        public Nullable<int> UserCompetitionCount { get; set; }
    
        public virtual City City { get; set; }
        public virtual RullTbl RullTbl { get; set; }
        public virtual State State { get; set; }
    }
}
